# Индивидуальное задание 1

>Создать ноутбук, в котором выполнить решение индивидуального задания. Ноутбук должен содержать условие индивидуального задания. При решении индивидуального задания не должны быть использованы условный оператор if, а также операторы циклов while и
for, а только средства библиотеки NumPy.

Дана целочисленная квадратная матрица.  
Определить:  
• произведение элементов в тех строках, которые не содержат отрицательных элементов;  
• максимум среди сумм элементов диагоналей, параллельных главной диагонали матрицы.  
Не должны быть использованы условный оператор if, а также операторы циклов while и
for, а только средства библиотеки NumPy.

In [1]:
import numpy as np

In [2]:
n = 5
a = np.random.randint(-10, 100, (n, n))
print(a)

[[11 -5 19 71 17]
 [61 59 15 -7 80]
 [34 34 73 18  8]
 [70 79 33 22  1]
 [54 67 57 22 33]]


In [3]:
pos_a = a[np.where(a.min(axis=1) > 0)].prod(axis=1)
print(f"Произведение в строках без отрицательных элементов: {pos_a}")

Произведение в строках без отрицательных элементов: [ 12151872   4014780 149720076]


In [4]:
maximum = max([
    sum(np.diag(a, k=-3)),
    sum(np.diag(a, k=-2)),
    sum(np.diag(a, k=-1)),
    sum(np.diag(a, k=1)),
    sum(np.diag(a, k=2)),
    sum(np.diag(a, k=3))])
print(f"Максимум среди сумм элементов диагоналей, параллельных главной диагонали: {maximum}")

Максимум среди сумм элементов диагоналей, параллельных главной диагонали: 170
