# Индивидуальное задание 1
Дана целочисленная квадратная матрица.  
Определить:  
• произведение элементов в тех строках, которые не содержат отрицательных элементов;  
• максимум среди сумм элементов диагоналей, параллельных главной диагонали матрицы.  
Не должны быть использованы условный оператор if, а также операторы циклов while и
for, а только средства библиотеки NumPy.

In [1]:
import numpy as np

In [2]:
n = 5
a = np.random.randint(-10, 100, (n, n))
print(a)

5
[[65 12 86 89 62]
 [81 61 12 14 58]
 [46  9 67 77 77]
 [34 31 63 56 36]
 [-2  3 34  7 19]]


In [3]:
pos_a = a[np.where(a.min(axis=1) > 0)].prod(axis=1)
print(f"Произведение в строках без отрицательных элементов: {pos_a}")

Произведение в строках без отрицательных элементов: [370147440  48145104 164458602 133866432]


In [7]:
maximum = max([
    sum(np.diag(a, k=-3)),
    sum(np.diag(a, k=-2)),
    sum(np.diag(a, k=-1)),
    sum(np.diag(a, k=1)),
    sum(np.diag(a, k=2)),
    sum(np.diag(a, k=3))])
print(f"Максимум среди сумм элементов диагоналей, параллельных главной диагонали: {maximum}")

Максимум среди сумм элементов диагоналей, параллельных главной диагонали: 177
